# -*- coding: utf-8 -*-
"""ai10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb3BDa0Crwt89kpYKqTQQLTFZxvqM2ps
"""

import random

# -------------------------------
# Scenario Class
# -------------------------------
class Scenario:
    def __init__(self, passengers, pedestrians, pedestrian_age_group):
        self.passengers = passengers
        self.pedestrians = pedestrians
        self.pedestrian_age_group = pedestrian_age_group  # child, adult, elderly

    def display(self):
        print("\n--- Ethical Scenario ---")
        print(f"Passengers           : {self.passengers}")
        print(f"Pedestrians          : {self.pedestrians}")
        print(f"Pedestrian Type      : {self.pedestrian_age_group}")


# -------------------------------
# Ethical AI System with Scoring
# -------------------------------
class EthicalAI:
    def __init__(self):
        # Assign weights (ethical importance)
        self.weights = {
            "passenger": 1.0,
            "pedestrian": 1.2,
            "child_bonus": 1.5,
            "elderly_bonus": 1.2
        }

    def calculate_score(self, scenario):
        # Base scores
        passenger_score = scenario.passengers * self.weights["passenger"]
        pedestrian_score = scenario.pedestrians * self.weights["pedestrian"]

        # Apply fairness / vulnerability bonus
        if scenario.pedestrian_age_group == "child":
            pedestrian_score *= self.weights["child_bonus"]
        elif scenario.pedestrian_age_group == "elderly":
            pedestrian_score *= self.weights["elderly_bonus"]

        return passenger_score, pedestrian_score

    def decide(self, scenario):
        p_score, ped_score = self.calculate_score(scenario)

        print(f"Passenger Score      : {p_score:.2f}")
        print(f"Pedestrian Score     : {ped_score:.2f}")

        if ped_score > p_score:
            return "Save pedestrians (higher ethical weight)"
        elif p_score > ped_score:
            return "Protect passengers"
        else:
            return "Equal ethical score → Random decision"


# -------------------------------
# Simulation
# -------------------------------
def simulate():
    passengers = random.randint(1, 5)
    pedestrians = random.randint(1, 5)
    age_group = random.choice(["child", "adult", "elderly"])

    scenario = Scenario(passengers, pedestrians, age_group)
    ai = EthicalAI()

    scenario.display()
    decision = ai.decide(scenario)

    print(f"Final Decision       : {decision}")


# -------------------------------
# Run Multiple Simulations
# -------------------------------
if __name__ == "__main__":
    print("AI Ethical Dilemma Simulation (Scoring Model)")

    for i in range(5):
        print(f"\nSimulation {i+1}")
        simulate()

import random

# -------------------------------
# Patient Class
# -------------------------------
class Patient:
    def __init__(self, name, age, survival_chance, severity):
        self.name = name
        self.age = age
        self.survival_chance = survival_chance  # 0 to 1
        self.severity = severity  # 1 (low) to 10 (critical)

    def display(self):
        print(f"{self.name} -> Age: {self.age}, Survival Chance: {self.survival_chance}, Severity: {self.severity}")


# -------------------------------
# Ethical Decision System
# -------------------------------
class HospitalAI:
    def __init__(self, policy="balanced"):
        self.policy = policy

    def decide(self, p1, p2):
        print(f"\nPolicy Used: {self.policy}")

        if self.policy == "survival_priority":
            return p1 if p1.survival_chance > p2.survival_chance else p2

        elif self.policy == "severity_priority":
            return p1 if p1.severity > p2.severity else p2

        elif self.policy == "young_priority":
            return p1 if p1.age < p2.age else p2

        elif self.policy == "balanced":
            score1 = (p1.survival_chance * 0.5) + (p1.severity * 0.3) + ((100 - p1.age) * 0.2)
            score2 = (p2.survival_chance * 0.5) + (p2.severity * 0.3) + ((100 - p2.age) * 0.2)

            print(f"{p1.name} Score: {round(score1,2)}")
            print(f"{p2.name} Score: {round(score2,2)}")

            return p1 if score1 > score2 else p2

        else:
            return None


# -------------------------------
# Simulation
# -------------------------------
def simulate():
    # Generate random patients
    p1 = Patient("Patient A", random.randint(10, 80), round(random.uniform(0.3, 0.9), 2), random.randint(1, 10))
    p2 = Patient("Patient B", random.randint(10, 80), round(random.uniform(0.3, 0.9), 2), random.randint(1, 10))

    print("\n--- ICU Allocation Scenario ---")
    p1.display()
    p2.display()

    policies = ["survival_priority", "severity_priority", "young_priority", "balanced"]
    ai = HospitalAI(random.choice(policies))

    selected = ai.decide(p1, p2)

    print(f"\nSelected for ICU: {selected.name}")


# -------------------------------
# Run
# -------------------------------
if __name__ == "__main__":
    print("Healthcare AI Ethical Dilemma Simulation")

    for i in range(3):
        print(f"\nSimulation {i+1}")
        simulate()

